# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Team.create([
  { name: "システム部" },
  { name: "インフラ部" },
  { name: "テレコム" },
  { name: "PBT" },
  { name: "BMW" },
  { name: "BMWワランティ" },
  { name: "CLSメーカー" },
  { name: "CostomerTouchPoint" },
  { name: "CRM24" },
  { name: "CRM保証" },
  { name: "CRM共通" },
  { name: "JA" },
  { name: "NFS" },
  { name: "NW管理室" },
  { name: "OAC" },
  { name: "OTAI" },
  { name: "PAD" },
  { name: "PHS" },
  { name: "SUBARUお客様センター" },
  { name: "SUBARU安心ほっとライン" },
  { name: "アドミニ" },
  { name: "イオンリテール" },
  { name: "カスタマー" },
  { name: "ソニー損保" },
  { name: "タイムコマース" },
  { name: "パークアシスト" },
  { name: "ビズネット" },
  { name: "プラス" },
  { name: "プレミオ" },
  { name: "プロパティシステム" },
  { name: "プロモーション" },
  { name: "ホームインフォメーション" },
  { name: "ホームレスキュー" },
  { name: "ロードリース" },
  { name: "人事" },
  { name: "住友三井" },
  { name: "少額短期" },
  { name: "情報管理" },
  { name: "損保共通" },
  { name: "日予" },
  { name: "業務管理" },
  { name: "瑕疵" },
  { name: "生保代理店" },
  { name: "経理" },
  { name: "財務経理" }
])

System.create([
  { name: "ActiveDirectory" ,description: "", is_active: true },
  { name: "ファイルサーバー" ,description: "", is_active: true },
  { name: "WSUS" ,description: "", is_active: true },
  { name: "統合バックアップ" ,description: "", is_active: true },
  { name: "CSIM" ,description: "", is_active: true },
  { name: "Chronos" ,description: "", is_active: true },
  { name: "BPS精査システム" ,description: "", is_active: true },
  { name: "BSN" ,description: "", is_active: true },
  { name: "NEEDS" ,description: "秋田ソリューションレポートシステム", is_active: true },
  { name: "Path Connect System2" ,description: "", is_active: true },
  { name: "Premier Customer Support（PCS）" ,description: "", is_active: true },
  { name: "Premio" ,description: "", is_active: true },
  { name: "アウトコールシステム" ,description: "", is_active: true },
  { name: "エース保険　プロテクトＹＯＵ　契約確認システム" ,description: "", is_active: true },
  { name: "OALS" ,description: "オリックス自動車事故受付システム", is_active: true },
  { name: "CCSS24" ,description: "カードカスタマーサービスシステム", is_active: true },
  { name: "けいすけくん" ,description: "経費振替管理システム", is_active: true },
  { name: "高速検索くん" ,description: "高速道路・インターチェンジ検索", is_active: true },
  { name: "FARCON" ,description: "スバルお客様相談室", is_active: true },
  { name: "TAURUS" ,description: "スバル保険事故受付システム", is_active: true },
  { name: "ZIP" ,description: "チューリッヒ事故受付システム", is_active: true },
  { name: "Garnet" ,description: "ニッポンレンタカー事故受付システム", is_active: true },
  { name: "プロパティ WEB領収" ,description: "", is_active: true },
  { name: "プロパティ 三井住友海上・ココロとカラダの安心メニュー" ,description: "", is_active: true },
  { name: "ECOS" ,description: "ヤナセ事故受付システム", is_active: true },
  { name: "ロータスシステム" ,description: "ロータス会員検索システム", is_active: true },
  { name: "ロータス車検受付システム" ,description: "", is_active: true },
  { name: "延長保証精査システム" ,description: "", is_active: true },
  { name: "SMAS" ,description: "住友三井オートサービス 契約検索サブシステム", is_active: true },
  { name: "OTAI" ,description: "新保険業務管理システム", is_active: true },
  { name: "OASYS" ,description: "日産フィナンシャル事故受付", is_active: true },
  { name: "瑕疵システム" ,description: "", is_active: true },
  { name: "Premier-net2" ,description: "", is_active: true },
  { name: "SumWell" ,description: "OASYS 集計ツール", is_active: true },
  { name: "出光オートフラット" ,description: "", is_active: true },
  { name: "PAMNAS" ,description: "PSAP緊急通報サービス", is_active: true },
  { name: "TKN" ,description: "BMW JF発送管理システム", is_active: true },
  { name: "Premier-net" ,description: "", is_active: true },
  { name: "SBI事故受付システム" ,description: "", is_active: true }
])

Server.create([
  { hostname: 'AK2OPMWB01', description: '', url: 'http://glpi.prestigein.local/glpi/front/computer.form.php?id=2' },
  { hostname: 'AKPNSBKSV01', description: '', url: 'http://glpi.prestigein.local/glpi/front/computer.form.php?id=3' },
  { hostname: 'AK2SV11', description: '', url: 'http://glpi.prestigein.local/glpi/front/computer.form.php?id=4' },
  { hostname: 'AK2SV12', description: '', url: 'http://glpi.prestigein.local/glpi/front/computer.form.php?id=5' },
  { hostname: 'AKDSSV01', description: '', url: 'http://glpi.prestigein.local/glpi/front/computer.form.php?id=6' },
  { hostname: 'AK2VLSV10', description: '', url: 'http://glpi.prestigein.local/glpi/front/computer.form.php?id=12' },
  { hostname: 'AK2IHSSV01', description: '', url: 'http://glpi.prestigein.local/glpi/front/computer.form.php?id=13' },
  { hostname: 'AK2WIKISV01', description: '', url: 'http://glpi.prestigein.local/glpi/front/computer.form.php?id=14' },
  { hostname: 'AK2KMSESX01', description: '', url: 'http://glpi.prestigein.local/glpi/front/computer.form.php?id=15' },
  { hostname: 'AK2KMSESX02', description: '', url: 'http://glpi.prestigein.local/glpi/front/computer.form.php?id=16' },
  { hostname: 'AK2OACJKDB01', description: '', url: 'http://glpi.prestigein.local/glpi/front/computer.form.php?id=17' },
  { hostname: 'AK2OACJKWEB01', description: '', url: 'http://glpi.prestigein.local/glpi/front/computer.form.php?id=18' },
  { hostname: 'AK2OACJKFX01', description: '', url: 'http://glpi.prestigein.local/glpi/front/computer.form.php?id=19' },
  { hostname: 'AK2HULFT01', description: '', url: 'http://glpi.prestigein.local/glpi/front/computer.form.php?id=20' },
  { hostname: 'AK2SUBPSV01', description: '', url: 'http://glpi.prestigein.local/glpi/front/computer.form.php?id=21' },
  { hostname: 'AK2SUBPSV02', description: '', url: 'http://glpi.prestigein.local/glpi/front/computer.form.php?id=22' },
  { hostname: 'ak2subpsv03', description: '', url: 'http://glpi.prestigein.local/glpi/front/computer.form.php?id=23' },
  { hostname: 'AKVLSV01', description: '', url: 'http://glpi.prestigein.local/glpi/front/computer.form.php?id=24' },
  { hostname: 'AK2VLSV01', description: '', url: 'http://glpi.prestigein.local/glpi/front/computer.form.php?id=25' },
  { hostname: 'AK2NFSDB02', description: '', url: 'http://glpi.prestigein.local/glpi/front/computer.form.php?id=26' },
  { hostname: 'AK2NFSFX02', description: '', url: 'http://glpi.prestigein.local/glpi/front/computer.form.php?id=27' },
  { hostname: 'AK2SYSSV01', description: '', url: 'http://glpi.prestigein.local/glpi/front/computer.form.php?id=28' },
  { hostname: 'AK2SYSSV02', description: '', url: 'http://glpi.prestigein.local/glpi/front/computer.form.php?id=29' },
  { hostname: 'AK2SV13', description: '', url: 'http://glpi.prestigein.local/glpi/front/computer.form.php?id=30' },
  { hostname: 'AK2SV14', description: '', url: 'http://glpi.prestigein.local/glpi/front/computer.form.php?id=31' },
  { hostname: 'zilwan', description: '', url: 'http://glpi.prestigein.local/glpi/front/computer.form.php?id=32' },
  { hostname: 'tiltowaito', description: '', url: 'http://glpi.prestigein.local/glpi/front/computer.form.php?id=33' },
  { hostname: 'WIN-BQPCJ07TGKL', description: '', url: 'http://glpi.prestigein.local/glpi/front/computer.form.php?id=34' },
  { hostname: 'AK2ONBASESV03', description: '', url: 'http://glpi.prestigein.local/glpi/front/computer.form.php?id=36' },
  { hostname: 'AK2ONBASESV04', description: '', url: 'http://glpi.prestigein.local/glpi/front/computer.form.php?id=37' },
  { hostname: 'AK2LOTASDB02', description: '', url: 'http://glpi.prestigein.local/glpi/front/computer.form.php?id=38' },
  { hostname: 'AK2IDCSTHSV10', description: '', url: 'http://glpi.prestigein.local/glpi/front/computer.form.php?id=39' },
  { hostname: 'AKCSIMSTDB01', description: '', url: 'http://glpi.prestigein.local/glpi/front/computer.form.php?id=41' },
  { hostname: 'AK2CSIMSV02', description: '', url: 'http://glpi.prestigein.local/glpi/front/computer.form.php?id=42' },
  { hostname: 'AK2CSIMSV13', description: '', url: 'http://glpi.prestigein.local/glpi/front/computer.form.php?id=43' },
  { hostname: 'AK2CSIMSV14', description: '', url: 'http://glpi.prestigein.local/glpi/front/computer.form.php?id=44' },
  { hostname: 'AK2CSIMSV210', description: '', url: 'http://glpi.prestigein.local/glpi/front/computer.form.php?id=45' },
  { hostname: 'AK2CSIMSV16', description: '', url: 'http://glpi.prestigein.local/glpi/front/computer.form.php?id=46' },
  { hostname: 'AK2CSIMSV211', description: '', url: 'http://glpi.prestigein.local/glpi/front/computer.form.php?id=47' },
  { hostname: 'AK2CSIMSV18', description: '', url: 'http://glpi.prestigein.local/glpi/front/computer.form.php?id=48' },
  { hostname: 'AK2CSIMSV40', description: '', url: 'http://glpi.prestigein.local/glpi/front/computer.form.php?id=49' },
  { hostname: 'AK2CSIMSV39', description: '', url: 'http://glpi.prestigein.local/glpi/front/computer.form.php?id=50' },
  { hostname: 'AK2CSIMSV53', description: '', url: 'http://glpi.prestigein.local/glpi/front/computer.form.php?id=51' },
  { hostname: 'AK2CSIMSV54', description: '', url: 'http://glpi.prestigein.local/glpi/front/computer.form.php?id=52' },
  { hostname: 'AK2CSIMSV55', description: '', url: 'http://glpi.prestigein.local/glpi/front/computer.form.php?id=53' },
  { hostname: 'AK2CSIMSV56', description: '', url: 'http://glpi.prestigein.local/glpi/front/computer.form.php?id=54' },
  { hostname: 'AK2CSIMSV57', description: '', url: 'http://glpi.prestigein.local/glpi/front/computer.form.php?id=55' },
  { hostname: 'AK2CSIMSV58', description: '', url: 'http://glpi.prestigein.local/glpi/front/computer.form.php?id=56' },
  { hostname: 'AK2CSIMSV03', description: '', url: 'http://glpi.prestigein.local/glpi/front/computer.form.php?id=57' },
  { hostname: 'AK2CSIMSV05', description: '', url: 'http://glpi.prestigein.local/glpi/front/computer.form.php?id=58' }
])